name: Fetch GitHub Repos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch repos and save to JSON
        run: |
          mkdir -p src/data
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/users/keepsake666/repos?per_page=100&type=public&sort=updated" \
            | jq '[.[] | {id, name, full_name, description, html_url, homepage, language, stargazers_count, forks_count, updated_at, topics, visibility, private, fork, owner: {login, avatar_url}, license}]' \
            > src/data/repos.json

      - name: Commit and push
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/keepsake666/portfolio-app.git"
          git remote -v
          echo "Token length: ${#GH_TOKEN}"
          git add src/data/repos.json
          git commit -m "Update repos.json [skip ci]" || echo "No changes"
          git push origin HEAD:main
